<form method="POST" action="" id="seoSubmit" class="service-form">
	<div class="column label">
		<span>Website-Check:</span>
	</div>
	<div class="column domain">
		<?php echo $form->renderDecorated("domain") ?>
	</div>
	<div class="column keyword">
		<?php echo $form->renderDecorated("keyword") ?>
	</div>
	<div class="column button">
		<?php echo $form->render("Check") ?>
	</div>
<!--	
	<div class="messages">
		<?php echo $form->messages("keyword") ?>
		<?php echo $form->messages("domain") ?>
	</div>-->
	
	<?php /*echo $form->render("csrf", array('value' => $this->security->getToken())) ?>
	<?php echo $form->messages("csrf") */?>
	
	<div id="disOver" class="disable-overlay">
		<?php echo $this->tag->image('img/ajax-loader.gif'); ?>
	</div>
</form>
<script>
	(function() {
		var disOver = document.getElementById('disOver'),
			seoSubmit = document.getElementById('seoSubmit');
			
		seoSubmit.onsubmit = function() {
			disOver.className += ' active';
		};
	})();
</script>
