<?php

 use Phalcon\Tag as Tag ?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<?php
		echo Tag::getTitle();
		echo Tag::stylesheetLink($this->config->baseUrl . 'css/main.css');
		?>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<div class="content">
			<?php echo $this->getContent(); ?>

<?php //echo Tag::javascriptInclude('js/jquery.min.js');  ?>
		</div>
	</body>
</html>